include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    always_declare_return_types: warning
    avoid_dynamic_calls: warning
    avoid_returning_null_for_future: warning
    avoid_void_async: warning
    cast_nullable_to_non_nullable: warning
    deprecated_consistency: warning
    invalid_annotation_target: ignore
    null_check_on_nullable_type_parameter: warning
    type_annotate_public_apis: warning
    unawaited_futures: warning
    use_build_context_synchronously: warning
    use_late_for_private_fields_and_variables: warning
  exclude:
    - "**.config.dart"
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "**.mocks.dart"
  language:
    strict-inference: true
    strict-raw-types: true
  plugins:
    - dart_code_metrics
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

dart_code_metrics:
  rules-exclude:
    - lib/gen/**
    - test/**
  rules:
    - avoid-cascade-after-if-null
    - avoid-collection-methods-with-unrelated-types
    - avoid-duplicate-exports
    - avoid-global-state
    - avoid-missing-enum-constant-in-map
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - double-literal-format
    - no-boolean-literal-compare
    - prefer-commenting-analyzer-ignores
    - prefer-first
    - prefer-immediate-return
    - prefer-iterable-of
    - prefer-last
    - prefer-trailing-comma
    - always-remove-listener
    - avoid-border-all
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object
    - prefer-const-border-radius
    - prefer-correct-edge-insets-constructor

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_dynamic_calls
    - avoid_field_initializers_in_const_classes
    - avoid_implementing_value_types
    - avoid_multiple_declarations_per_line
    - avoid_private_typedef_functions
    - avoid_returning_null_for_future
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_type_to_string
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - close_sinks
    - comment_references
    - deprecated_consistency
    - directives_ordering
    - eol_at_end_of_file
    - invariant_booleans
    - join_return_with_assignment
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_runtimeType_toString
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - omit_local_variable_types
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_constructors_over_static_methods
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - sort_child_properties_last
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unsafe_html
    - use_build_context_synchronously
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_setters_to_change_properties
    - use_string_buffers
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
